//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
namespace Kneeboard_Picture_Viewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
		[Category("Folder Pane")]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Info")]
        public global::System.Drawing.Color Folder_Background {
            get {
                return ((global::System.Drawing.Color)(this["Folder_Background"]));
            }
            set {
                this["Folder_Background"] = value;
            }
        }
        
		[Category("Folder Pane")]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 9.75pt, style=Bold")]
        public global::System.Drawing.Font Folder_Button_Font {
            get {
                return ((global::System.Drawing.Font)(this["Folder_Button_Font"]));
            }
            set {
                this["Folder_Button_Font"] = value;
            }
        }
        
		[Category("Folder Pane")]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color Folder_Button_Background {
            get {
                return ((global::System.Drawing.Color)(this["Folder_Button_Background"]));
            }
            set {
                this["Folder_Button_Background"] = value;
            }
        }
        
		[Category("File Pane")]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MenuBar")]
        public global::System.Drawing.Color File_Background {
            get {
                return ((global::System.Drawing.Color)(this["File_Background"]));
            }
            set {
                this["File_Background"] = value;
            }
        }
        
		[Category("File Pane")]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 9.75pt")]
        public global::System.Drawing.Font File_Button_Font {
            get {
                return ((global::System.Drawing.Font)(this["File_Button_Font"]));
            }
            set {
                this["File_Button_Font"] = value;
            }
        }
        
		[Category("File Pane")]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YellowGreen")]
        public global::System.Drawing.Color File_Button_Background {
            get {
                return ((global::System.Drawing.Color)(this["File_Button_Background"]));
            }
            set {
                this["File_Button_Background"] = value;
            }
        }
        
		[Category("Program")]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color Buttons_Background {
            get {
                return ((global::System.Drawing.Color)(this["Buttons_Background"]));
            }
            set {
                this["Buttons_Background"] = value;
            }
        }
        
		[Category("Program")]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Kneeboard_Images_Directory {
            get {
                return ((string)(this["Kneeboard_Images_Directory"]));
            }
            set {
                this["Kneeboard_Images_Directory"] = value;
            }
        }
        
		[Category("Program")]
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Close_Navigation {
            get {
                return ((bool)(this["Close_Navigation"]));
            }
            set {
                this["Close_Navigation"] = value;
            }
        }
    }
}
